// Generated by BUCKLESCRIPT VERSION 4.0.1100, PLEASE EDIT WITH CARE
'use strict';

var Reprocessing = require("/Users/chihching/reprocessing-fruit-ninja/node_modules/reprocessing/lib/js/src/Reprocessing.js");

Reprocessing.hotreload(undefined, "src/index.re");

/*  Not a pure module */
